import { supabaseClient } from "@/services/supabase/supabase.client";
import type { IFinanceiroRepository } from "@/shared/interfaces/IFinanceiroRepository";
import type { CreateLancamentoInput, LancamentoFinanceiro, ResumoFinanceiro } from "@/specs/schemas/financeiro.schema";
type Row={id:string;user_id:string;tipo:LancamentoFinanceiro["tipo"];descricao:string;categoria:string;valor:number|string;competencia:string;vencimento:string|null;pago_em:string|null;forma_pagamento:string|null;status:LancamentoFinanceiro["status"];processo_id:string|null;cliente_id:string|null;parcela_numero:number|null;parcelas_total:number|null;criado_em:string;atualizado_em:string};
const map=(r:Row):LancamentoFinanceiro=>({id:r.id,userId:r.user_id,tipo:r.tipo,descricao:r.descricao,categoria:r.categoria,valor:Number(r.valor),competencia:r.competencia,...(r.vencimento?{vencimento:r.vencimento}:{}),...(r.pago_em?{pagoEm:r.pago_em}:{}),...(r.forma_pagamento?{formaPagamento:r.forma_pagamento}:{}),status:r.status,...(r.processo_id?{processoId:r.processo_id}:{}),...(r.cliente_id?{clienteId:r.cliente_id}:{}),...(r.parcela_numero?{parcelaNumero:r.parcela_numero}:{}),...(r.parcelas_total?{parcelasTotal:r.parcelas_total}:{}),criadoEm:r.criado_em,atualizadoEm:r.atualizado_em});
export class SupabaseFinanceiroAdapter implements IFinanceiroRepository{
 public async listar(userId:string,inicio:string,fim:string):Promise<LancamentoFinanceiro[]>{const{data,error}=await supabaseClient.from("lancamentos_financeiros").select("*").eq("user_id",userId).gte("competencia",inicio).lte("competencia",fim).order("competencia",{ascending:false});if(error)throw new Error("Erro ao carregar financeiro.");return(data as Row[]).map(map)}
 public async criar(userId:string,d:CreateLancamentoInput):Promise<LancamentoFinanceiro>{const{data,error}=await supabaseClient.from("lancamentos_financeiros").insert({user_id:userId,...d}).select().single<Row>();if(error||!data)throw new Error("Erro ao criar lançamento.");return map(data)}
 public async resumo(userId:string,inicio:string,fim:string):Promise<ResumoFinanceiro>{const itens=await this.listar(userId,inicio,fim);return itens.reduce((a,i)=>({receitas:a.receitas+(i.tipo==="RECEITA"&&i.status==="PAGO"?i.valor:0),despesas:a.despesas+(i.tipo==="DESPESA"&&i.status==="PAGO"?i.valor:0),saldo:a.saldo+(i.status==="PAGO"?(i.tipo==="RECEITA"?i.valor:-i.valor):0),pendente:a.pendente+(i.status==="PENDENTE"?i.valor:0),atrasado:a.atrasado+(i.status==="ATRASADO"?i.valor:0)}),{receitas:0,despesas:0,saldo:0,pendente:0,atrasado:0})}
 public async excluir(userId:string,id:string):Promise<void>{const{error}=await supabaseClient.from("lancamentos_financeiros").delete().eq("id",id).eq("user_id",userId);if(error)throw new Error("Erro ao excluir lançamento.")}
}
